# Generated by Django 4.0.1 on 2022-01-23 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_license', models.CharField(max_length=9)),
                ('vehicle_type', models.CharField(choices=[('X', 'zberX'), ('L', 'zberXL'), ('S', 'zberSUV'), ('U', 'zberLUX')], max_length=1)),
                ('VIN', models.CharField(max_length=17)),
                ('license_plate', models.CharField(max_length=10)),
                ('max_passengers', models.IntegerField()),
                ('special_info', models.CharField(max_length=200, null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
