# Generated by Django 4.0.1 on 2022-01-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_users_driver_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
