# Generated by Django 4.0.1 on 2022-01-24 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_rename_user_id_driver_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Owner',
            fields=[
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sum_owners', models.IntegerField()),
                ('specific_type', models.CharField(choices=[('X', 'zberX'), ('L', 'zberXL'), ('S', 'zberSUV'), ('U', 'zberLUX')], max_length=1, null=True)),
                ('special_requests', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='riders.ride_owner')),
                ('dest_addr', models.CharField(max_length=30)),
                ('arrival_time', models.DateTimeField()),
                ('sum_passengers', models.IntegerField()),
                ('share', models.BooleanField()),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'confirmed'), ('t', 'complete')], max_length=1)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Ride_Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_sharers', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.ride')),
            ],
            options={
                'unique_together': {('user', 'ride')},
            },
        ),
    ]
