# Generated by Django 4.0.1 on 2022-01-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user_id',
            new_name='user',
        ),
    ]
