# Generated by Django 4.0.1 on 2022-01-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_owner',
            name='order_no',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
