# Generated by Django 2.2.26 on 2022-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_alter_ride_driver_alter_ride_owner_special_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_sharer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
